name: zap_baseline_scan
on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  zap_base_scan:
    name : web application base_scan
    runs-on: ubuntu-20.04
    permissions: 
      issues: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://127.0.0.1:3000' # target: 'https://localhost:3000'
          cmd_options: '-a'
