name: zap_baseline_scan
on:
  workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    #permissions: write-all
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:3000'
          #target: 'http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):3000'
          #rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d -T 5 -m 2'
