name: zap_full_scan #Running the OWASP ZAP Full Scan to perform Dynamic Application Security Testing (DAST).
on:
#  push:
#    branches:
#      - main
#  pull_request:
#  workflow_call:
  workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-20.04
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://127.0.0.1:3000/#/'
          #rules_file_name: '.zap/rules.tsv'
          #cmd_options: '-a'
